analyses_a_odds_ratios = {'age': {'mean': 1.10,
                                  'lower_ci': 1.03,
                                  'upper_ci': 1.17},
                          'heart': {'mean': 2.14,
                                    'lower_ci': 0.26,
                                    'upper_ci': 17.79},
                          'sofa': {'mean': 5.65,
                                   'lower_ci': 2.61,
                                   'upper_ci': 12.23},
                          'lymphocyte': {'mean': 0.19,
                                         'lower_ci': 0.02,
                                         'upper_ci': 1.62},
                          'd_dimer_middle': {'mean': 2.14,
                                             'lower_ci': 0.21,
                                             'upper_ci': 21.39},
                          'd_dimer_high': {'mean': 18.42,
                                           'lower_ci': 2.64,
                                           'upper_ci': 128.55},
                          }

analyses_b_estimates = {'intercept': {'estimate': -12.73,
                                      'se': 3.1},
                        'age': {'estimate': 0.096,
                                'se': 0.033},
                        'heart': {'estimate': 1,
                                  'se': 1.16},
                        'sofa': {'estimate': 1.73,
                                 'se': 0.40},
                        'lymphocyte': {'estimate': -1.63,
                                       'se': 1.11},
                        'd_dimer_middle': {'estimate': 0.58,
                                           'se': 1.23},
                        'd_dimer_high': {'estimate': 2.67,
                                         'se': 1.05},
                        }
